version: '3.8'
services:
  web:
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_URI=mongodb://mongo:27017/docker-node-mongo
    restart: unless-stopped
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: