# Use the official MongoDB image from the Docker Hub
FROM mongo:latest

# Set environment variables

# Optional: Copy initialization scripts to the container
# Uncomment the following lines if you have any scripts to run on startup
# COPY ./init-mongo.js /docker-entrypoint-initdb.d/

# Expose the default MongoDB port
EXPOSE 27017
